FX2LIBDIR=../../../
BASENAME = cdc-acm-to-uart
SOURCES=../common/main.c ../common/cdc.c
DEPS=../common/cdc.h ../common/cdc-config.h
INCLUDES=../common
A51_SOURCES=../common/dscr.a51
PID=0x1004

include $(FX2LIBDIR)lib/fx2.mk
