FX2LIBDIR=../../../
BASENAME = cdc-acm-loopback
SOURCES=../common/main.c ../common/cdc.c
DEPS=../common/cdc.h ../common/cdc-config.h main-custom.c
INCLUDES=../common -I ./
A51_SOURCES=../common/dscr.a51
PID=0x1004

include $(FX2LIBDIR)lib/fx2.mk
